FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

RUN mkdir -p uploads

COPY . .

RUN pnpm install
RUN rm -rf dist
RUN pnpm build

EXPOSE 3000

CMD ["node", "dist/main"]